version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbfile:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp_net

  wordpress:
    image: wordpress:6.1.1-php8.0-fpm
    container_name: 6.1.1-php8.0-fpm
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - www-html:/var/www/html
    networks:
      - wp_net

  varnish:
    image: varnish:7.2.1
    container_name: varnish7
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./varnish:/etc/varnish
    networks:
      - wp_net

  nginx:
    image: nginx:1.23.3-alpine
    depends_on:
      - wordpress
    container_name: nginx-1.23.3-alpine
    restart: unless-stopped
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
    networks:
      - wp_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: phpmyadmin-5.0.0
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmin:/usr/src/phpmyadmin
    depends_on:
      - mysql
    networks:
      - wp_net

volumes:
  www-html:
  dbfile:
  phpmyadmin:

networks:
  wp_net:
    driver: bridge
